config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'resource' => 'static_pages#resource'

  resources :users
  get 'register'  => 'users#new'
  post 'users/:id/add_webops_skill/:skill' => 'users#add_webops_skill'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :skills

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def resource
    @skills = Skill.all
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="row">
    <div class="col-md-10 col-md-offset-1" id="contact-form">
        <iframe src="https://docs.google.com/forms/d/1IcPJ4c1P8X4zQq_hhbx_iSgaFVf3Fz3gspSJkugE0BI/viewform?embedded=true"
            height="500" frameborder="0" marginheight="0" marginwidth="0" class="col-md-12">
            Loading...
        </iframe>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
    <%= image_tag "logo_black.png", class: "col-md-12" %>
</div>
<% if not logged_in? %>
    <div class="row">
        <%= link_to "Register now!", register_path, class: "btn btn-default btn-lg col-md-4 col-md-offset-4" %>
    </div>
<% end %>

app/views/static_pages/resource.html.erb
<% provide(:title, "Resource") %>

<div class="panel-group" id="resource-accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#resource-accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          FRONTEND
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <% @skills.each do |skill| %>
          <% if skill.sub_category == "frontend" %>
          <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
            <%= image_tag "skills/#{skill.image_name}", height: "50px" %>
            <%= skill.name.upcase %>
          </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#resource-accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          BACKEND
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <% @skills.each do |skill| %>
          <% if skill.sub_category == "backend" %>
          <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
            <%= image_tag "skills/#{skill.image_name}", height: "50px" %>
            <%= skill.name.upcase %>
          </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#resource-accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          TUTORIAL
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <% @skills.each do |skill| %>
          <% if skill.sub_category == "tutorial" %>
          <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
            <%= image_tag "skills/#{skill.image_name}", height: "50px" %>
            <%= skill.name.upcase %>
          </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#resource-accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          SOFTWARE
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        <% @skills.each do |skill| %>
          <% if skill.sub_category == "software" %>
          <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
            <%= image_tag "skills/#{skill.image_name}", height: "50px" %>
            <%= skill.name.upcase %>
          </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>