config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'resource' => 'static_pages#resource'

  resources :users
  get 'register'  => 'users#new'
  post 'users/:id/add_webops_skill/:skill' => 'users#add_webops_skill'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :skills

end

app/models/skill.rb
class Skill < ActiveRecord::Base
    before_save :downcase_all
    private
        # Converts roll to all lower-case.
        def downcase_all
          self.name.downcase!
          self.link.downcase!
          self.image_name.downcase!
          self.category.downcase!
          self.sub_category.downcase!
        end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
   before_action :logged_in_user
   before_action :admin_user
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      # Handle a successful save.
      flash[:success] = "Skill successfully added"
      redirect_to skills_path
    else
      render 'new'
    end
  end

  def update
  end

  def index
    @skills = Skill.all
  end

  def show
  end

  def destroy
  end
end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :link, :image_name, :category, :sub_category)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_fields.html.erb
<%= render 'shared/error_messages' %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :image_name %>
    <%= f.text_field :image_name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :category, "Category" %>
    <%= f.select(:category) do %>
      <% [['WebOps', 'WebOps']].each do |c| -%>
        <%= content_tag(:option, c.first, value: c.last) %>
      <% end %>
    <% end %>
</div>
<div class="form-group">
    <%= f.label :sub_category, "Sub-category" %>
    <%= f.select(:sub_category) do %>
      <% [['Frontend', 'Frontend'],
          ['Backend', 'Backend'],
          ['Tutorial', 'Tutorial'],
          ['Software', 'Frontend']].each do |c| -%>
        <%= content_tag(:option, c.first, value: c.last) %>
      <% end %>
    <% end %>
</div>

app/views/skills/destroy.html.erb
<h1>Skills#destroy</h1>
<p>Find me in app/views/skills/destroy.html.erb</p>

app/views/skills/index.html.erb
<% provide(:title, 'All Skills') %>
<%= link_to "Add a skill", new_skill_path, class: "btn btn-info pull-right" %>
<h1>All Skills</h1>
<table class="table table-bordered table-striped" id="allSkillsTable">
  <thead>
    <th>ID</th>
    <th>NAME</th>
    <th>LINK</th>
    <th>IMAGE NAME</th>
    <th>CATEGORY</th>
    <th>SUB-CATEGORY</th>
  </thead>
  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.id %></td>
        <td><%= link_to skill.name.upcase!, skill %></td>
        <td><%= link_to skill.link, skill.link, target: "_blank" %></td>
        <td><%= image_tag "skills/#{skill.image_name}", height: "50px" %></td>
        <td><%= skill.category.capitalize! %></td>
        <td><%= skill.sub_category %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script>
  $(document).ready(function(){
    $('#allSkillsTable').DataTable({
      'pagingType': 'simple',
      'dom': "<'row'<'col-md-6'l><'col-md-6'f>><'row'<'col-md-6'i><'col-md-6'p>r>t<'row'<'col-md-6'l><'col-md-6'p>>",
    });
  });
</script>

app/views/skills/new.html.erb
<h1 class="text-center">Add a new skill</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@skill, html: {class: 'form'}) do |f|%>
      <%= render 'fields', f: f %>
      <div class="form-group">
        <%= f.submit "Create Skill", class: "btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/skills/show.html.erb
<h1>Skills#show</h1>
<p>Find me in app/views/skills/show.html.erb</p>

app/views/skills/update.html.erb
<h1>Skills#update</h1>
<p>Find me in app/views/skills/update.html.erb</p>