config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'resource' => 'static_pages#resource'

  resources :users
  get 'register'  => 'users#new'
  post 'users/:id/add_webops_skill/:skill' => 'users#add_webops_skill'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :skills

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsible-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<%= root_path %>" class="navbar-brand">
                <%= image_tag "logo_white_header.png", height: "50px" %>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="collapsible-navbar">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Resources",   resource_path %></li>
                <li><%= link_to "Contact Us", contact_path %></li>
                <li><%= link_to "About Us",   about_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "All Users", users_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <%= current_user.roll.upcase %> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title( yield(:title) ) %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  <%= render 'layouts/footer' %>
</body>
</html>